% Generates the header for the mex files translating ccode previously
% generated by 'genCcode'

addpath('ccode')
listing = dir('ccode/*.ccode');

for i = 1 : numel(listing)

    filename = listing(i).name;
    strID = filename(1:end-6); % remove '.ccode'
    prefix = strsplit(strID,'_');
    param_type = prefix(2);
    loss_type = prefix(3);
    
    [J, theta, rho, t] = ...
        settings_lqr3( loss_type, param_type );
    dim_rho = size(rho,2);
    
    header = strcat(['#ifndef ' strID '_H\n#define ' strID '_H\n']);
    
    fun_name = strcat(['double ' strID '(double* tv, int tdim, double* param, int pdim) {\n']);
    
    t_decl = strcat('double t1 = tv[0], t2 = tv[1];\n');
    
    r_decl = [];
    for j = 1 : dim_rho
        r_decl = strcat([r_decl 'double r' num2str(j) ' = param[' num2str(j-1) '];\n']);
    end
    
    text = fileread(filename);
    body = strrep(text, '  t', 'double t');
    
%     fileID = fopen(filename);
%     tline = fgetl(fileID);
%     body = strcat(['double' tline '\n']);
%     while tline ~= -1
%         tline = fgetl(fileID);
%         body = strcat([body strrep(tline, ';', ';\ndouble ')]);
%     end
%     fclose(fileID);

    footer = 'return t0;\n}\n\n#endif';
    
    fullText = sprintf([header '\n' fun_name '\n' t_decl '\n' r_decl '\n' body '\n' footer]);
    
    cName = strcat(['header/' strID '.h']);
    
    cFileID = fopen(cName,'w');
    fprintf(cFileID,'%s',fullText);
    
    fclose(cFileID);
    
end